### ISSUE TITLE
SilverStripe 4 support

### ISSUE THREAD

**Issue by nikrolls** [axllent/silverstripe-email-obfuscator#8]
Any plans for SilverStripe 4 support? It's about to come into Beta and I want to start compatibility work on our sites as early as possible.

**Comment by axllent** [comment]
Yes indeed there will be SilverStripe 4 support. Currently the documentation on 4 however is outdated (with regards to examples of namespacing etc), so I'm not sure what the *correct way* of implementing it is. Are you able to help?

I have had a play here with the alpha version and got this module working (see my [silverstripe4 branch](https://github.com/axllent/silverstripe-email-obfuscator/tree/silverstripe4)), however I won't release anything at this stage until I know I'm doing it right.

**Comment by nikrolls** [comment]
Awesome, thanks! Granted it's very early so I think for most people just having a branch they can point to so composer will install is a huge benefit (as you've done). SilverStripe's roadmap says that beta should be out soon, so I would think the documentation will be more up to date then and it will be a better time to start working on support.

**Comment by axllent** [comment]
I've just released a 2.0.0 version for SilverStripe 4 ;-)

**Comment by nikrolls** [comment]
Awesome, thanks very much @axllent!
